<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.aicas.osgi</groupId>
    <artifactId>service-loader</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>serviceloader-mediator</artifactId>
  <name>OSGi ServiceLoader Mediator</name>
  <packaging>bundle</packaging>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>${maven.bundle.plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Import-Package>
              org.osgi.framework;version="[1.8,2)",
              org.osgi.framework.hooks.weaving,
              org.osgi.framework.wiring,
              org.osgi.util.tracker,
              org.osgi.service.log,
              *
            </Import-Package>
            <Export-Package>com.aicas.osgi.spi.proxy</Export-Package>
            <Private-Package>com.aicas.osgi.spi.proxy.internal</Private-Package>
            <Provide-Capability>
              osgi.extender;osgi.extender="osgi.serviceloader.processor";version:Version="1.0.0",
              osgi.extender;osgi.extender="osgi.serviceloader.registrar";version:Version="1.0.0"
            </Provide-Capability>
            <Require-Capability>
              osgi.service;filter:="(objectClass=org.osgi.service.log.LogService)";effective:=active;resolution:=optional
            </Require-Capability>
            <Bundle-Activator>com.aicas.osgi.spi.proxy.internal.MediatorActivator</Bundle-Activator>
          </instructions>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>osgi.core</artifactId>
      <version>${osgi.core.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.util.tracker</artifactId>
      <version>${osgi.tracker.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.log</artifactId>
      <version>${osgi.log.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi</groupId>
      <artifactId>serviceloader-weaver</artifactId>
      <version>${revision}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymock</artifactId>
      <version>${easymock.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-subclass</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
