<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.aicas.osgi</groupId>
    <artifactId>service-loader</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>serviceloader-itests</artifactId>
  <name>OSGi ServiceLoader integration tests</name>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.framework</artifactId>
      <version>7.0.5</version>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>osgi.core</artifactId>
      <version>${osgi.core.version}</version>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.log</artifactId>
      <version>${osgi.log.version}</version>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.util.tracker</artifactId>
      <version>${osgi.tracker.version}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi</groupId>
      <artifactId>serviceloader-mediator</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi</groupId>
      <artifactId>serviceloader-weaver</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-spi-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-provider-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-embedded-consumer-bundle</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-consumer-update-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-unprocessed-consumer</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-provider-update-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-provider-moduleinfo-update-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-provider-failure-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-consumer-fragment-host</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-consumer-fragment</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-two-service-provider-host</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-two-service-provider-fragment</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-provider-moduleinfo-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-provider-consumer-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-provider-fragment-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-provider-fragment-host-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-consumer-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-osgi-client-example</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-subclass</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includes>
            <include>**/*IntegrationTest.java</include>
          </includes>
          <classpathDependencyExcludes>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-consumer-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-osgi-client-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-embedded-consumer</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-embedded-consumer-bundle</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-unprocessed-consumer</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-consumer-update-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-provider-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-provider-update-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-provider-moduleinfo-update-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-provider-failure-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-consumer-fragment-host</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-consumer-fragment</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-two-service-provider-host</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.testbundle:serviceloader-two-service-provider-fragment</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-provider-moduleinfo-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-provider-consumer-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-provider-fragment-example</classpathDependencyExclude>
            <classpathDependencyExclude>com.aicas.osgi.example:serviceloader-provider-fragment-host-example</classpathDependencyExclude>
          </classpathDependencyExcludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
