<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.aicas.osgi.testbundle</groupId>
    <artifactId>testbundles</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>serviceloader-consumer-fragment</artifactId>
  <packaging>bundle</packaging>
  <name>OSGi ServiceLoader consumer fragment test bundle</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>${maven.bundle.plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Fragment-Host>com.aicas.osgi.testbundle.serviceloader-consumer-fragment-host;bundle-version="[1.0.0,2.0.0)"</Fragment-Host>
            <Require-Capability>osgi.serviceloader; filter:="(osgi.serviceloader=com.aicas.osgi.spi.example.spi.SPIProvider)";cardinality:=multiple;resolution:=optional,osgi.extender; filter:="(osgi.extender=osgi.serviceloader.processor)"</Require-Capability>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>com.aicas.osgi.testbundle</groupId>
      <artifactId>serviceloader-consumer-fragment-host</artifactId>
      <version>${revision}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.aicas.osgi.example</groupId>
      <artifactId>serviceloader-spi-example</artifactId>
      <version>${revision}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
