/*------------------------------------------------------------------------*
 * Copyright 2026, aicas GmbH; all rights reserved.
 * This header, including copyright notice, may not be altered or removed.
 *------------------------------------------------------------------------*/

package com.aicas.osgi.spi.weaver;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Handle;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

/**
 * Unit tests for {@link ServiceLoaderWeaver}.
 *
 * <p>The tests generate synthetic Java class files directly with ASM rather
 * than compiling Java fixture source files. This makes it possible to control
 * the exact bytecode instruction owner, method descriptor, and invocation
 * opcode used in each test.</p>
 *
 * <p>The tests cover the following weaving rules:</p>
 *
 * <ul>
 *   <li>Supported {@code java.util.ServiceLoader} calls are rewritten to
 *       {@code com.aicas.osgi.spi.proxy.ServiceLoader}.</li>
 *   <li>Only the configured {@code INVOKESTATIC} and
 *       {@code INVOKEVIRTUAL} method invocations are accepted.</li>
 *   <li>An unsupported ServiceLoader invocation rejects the transformation of
 *       the complete class.</li>
 *   <li>Rejected or inapplicable transformations return the original byte
 *       array unchanged.</li>
 *   <li>When weaving succeeds, ServiceLoader references in method
 *       instructions, field descriptors, method descriptors, and generic
 *       signatures are remapped.</li>
 * </ul>
 *
 * <p>The generated classes are not written to files. They exist only as
 * byte arrays created by {@link ClassWriter} and inspected using
 * {@link ClassReader}.</p>
 */
public class ServiceLoaderWeaverTest
{
  /**
   * Verifies weaving of the standard one-argument ServiceLoader factory call.
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * java.util.ServiceLoader<Runnable> loader =
   *     java.util.ServiceLoader.load(Runnable.class);
   * }</pre>
   *
   * <p>The original invocation is:</p>
   *
   * <pre>
   * INVOKESTATIC java/util/ServiceLoader.load
   *   (Ljava/lang/Class;)Ljava/util/ServiceLoader;
   * </pre>
   *
   * <p>The expected woven invocation is:</p>
   *
   * <pre>
   * INVOKESTATIC com/aicas/osgi/spi/proxy/ServiceLoader.load
   *   (Ljava/lang/Class;)Lcom/aicas/osgi/spi/proxy/ServiceLoader;
   * </pre>
   */
  @Test
  public void weavesLoadWithServiceClass()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      method.visitLdcInsn(Type.getType(Runnable.class));

                      method.visitMethodInsn(Opcodes.INVOKESTATIC,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "load",
                                             "(Ljava/lang/Class;)Ljava/util/ServiceLoader;",
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKESTATIC,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "load",
                           "(Ljava/lang/Class;)" + ServiceLoaderWeaver.OSGI_SERVICE_LOADER_DESCRIPTOR);

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of ServiceLoader.load(Class, ClassLoader).
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * java.util.ServiceLoader<Runnable> loader =
   *     java.util.ServiceLoader.load(
   *         Runnable.class,
   *         classLoader);
   * }</pre>
   *
   * <p>Both the invocation owner and the return type in the descriptor must be
   * changed to {@code com/aicas/osgi/spi/proxy/ServiceLoader}. The ClassLoader argument remains
   * unchanged.</p>
   */
  @Test
  public void weavesLoadWithExplicitClassLoader()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      method.visitLdcInsn(Type.getType(Runnable.class));
                      method.visitInsn(Opcodes.ACONST_NULL);

                      method.visitMethodInsn(Opcodes.INVOKESTATIC,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "load",
                                             "(Ljava/lang/Class;Ljava/lang/ClassLoader;)" +
                                                 ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR,
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKESTATIC,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "load",
                           "(Ljava/lang/Class;Ljava/lang/ClassLoader;)" +
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER_DESCRIPTOR);

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of the instance method ServiceLoader.iterator().
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code Iterator<Runnable> iterator =
   *     java.util.ServiceLoader.load(Runnable.class).iterator();
   * }</pre>
   *
   * <p>The load invocation and the iterator invocation must both use
   * {@code com/aicas/osgi/spi/proxy/ServiceLoader} as their owner after weaving.</p>
   */
  @Test
  public void weavesIterator()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      emitLoad(method);

                      method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "iterator",
                                             "()Ljava/util/Iterator;",
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKEVIRTUAL,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "iterator",
                           "()Ljava/util/Iterator;");

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of ServiceLoader.reload().
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * java.util.ServiceLoader<Runnable> loader =
   *     java.util.ServiceLoader.load(Runnable.class);
   *
   * loader.reload();
   * }</pre>
   *
   * <p>The {@code reload()} method descriptor remains {@code ()V}; only the
   * invocation owner changes.</p>
   */
  @Test
  public void weavesReload()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      emitLoad(method);

                      method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "reload",
                                             "()V",
                                             false);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKEVIRTUAL,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "reload",
                           "()V");

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of ServiceLoader.findFirst().
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * Optional<Runnable> provider =
   *     java.util.ServiceLoader.load(Runnable.class).findFirst();
   * }</pre>
   *
   * <p>The return type {@code java.util.Optional} is not remapped because only
   * the ServiceLoader type is replaced.</p>
   */
  @Test
  public void weavesFindFirst()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      emitLoad(method);

                      method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "findFirst",
                                             "()Ljava/util/Optional;",
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKEVIRTUAL,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "findFirst",
                           "()Ljava/util/Optional;");

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of a toString() invocation whose bytecode owner is
   * java/util/ServiceLoader.
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code String text =
   *     java.util.ServiceLoader.load(Runnable.class).toString();
   * }</pre>
   *
   * <p>The method descriptor remains {@code ()Ljava/lang/String;}. Only the
   * invocation owner changes.</p>
   */
  @Test
  public void weavesToString()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
      {
        @Override
        public void accept(MethodVisitor method)
        {
          emitLoad(method);

          method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                 ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                 "toString",
                                 "()Ljava/lang/String;",
                                 false);

          method.visitInsn(Opcodes.POP);
        }
      });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKEVIRTUAL,
                           ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                           "toString",
                           "()Ljava/lang/String;");

    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies weaving of a method-reference constant targeting
   * {@code ServiceLoader.load(Class)}.
   *
   * <p>The method handle is represented by an {@code LDC} constant rather
   * than an ordinary invocation instruction. The handle owner and return type
   * descriptor must still be remapped.</p>
   */
  @Test
  public void weavesStaticServiceLoaderMethodReference()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
      {
        @Override
        public void accept(MethodVisitor method)
        {
          method.visitLdcInsn(new Handle(Opcodes.H_INVOKESTATIC,
                                         ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                         "load",
                                         "(Ljava/lang/Class;)" +
                                                 ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR,
                                         false));
          method.visitInsn(Opcodes.POP);
        }
      });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());
    assertNoReferenceToJavaServiceLoader(result.getBytes());
  }

  /**
   * Verifies that a method reference to unsupported {@code stream()} prevents
   * weaving, just like an ordinary {@code stream()} invocation.
   */
  @Test
  public void rejectsUnsupportedStreamMethodReference()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
      {
        @Override
        public void accept(MethodVisitor method)
        {
          method.visitLdcInsn(new Handle(Opcodes.H_INVOKEVIRTUAL,
                                         ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                         "stream",
                                         "()Ljava/util/stream/Stream;",
                                         false));
          method.visitInsn(Opcodes.POP);
        }
      });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());
  }

  /**
   * Verifies rejection of ServiceLoader.stream(), which is not included in the
   * configured supported-method set.
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * Stream<ServiceLoader.Provider<Runnable>> providers =
   *     java.util.ServiceLoader.load(Runnable.class).stream();
   * }</pre>
   *
   * <p>Although the preceding load(Class) call is supported, the unsupported
   * stream() call must reject weaving of the complete class. The result must
   * contain the exact original byte array.</p>
   */
  @Test
  public void rejectsUnsupportedStreamInvocation()
  {
    byte[] originalBytes = createClass(new MethodBody()
                                       {
                                         @Override
                                         public void accept(MethodVisitor method)
                                         {
                                           emitLoad(method);
                                           method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                                                  ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                                                  "stream",
                                                                  "()Ljava/util/stream/Stream;",
                                                                  false);
                                           method.visitInsn(Opcodes.POP);
                                         }
                                       });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());
    assertArrayEquals(originalBytes, result.getBytes());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKEVIRTUAL,
                           ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                           "stream",
                           "()Ljava/util/stream/Stream;");
  }

  /**
   * Verifies rejection of ServiceLoader.load(ModuleLayer, Class).
   *
   * <p>The generated bytecode represents:</p>
   *
   * <pre>{@code
   * java.util.ServiceLoader<Runnable> loader =
   *     java.util.ServiceLoader.load(
   *         moduleLayer,
   *         Runnable.class);
   * }</pre>
   *
   * <p>This overload has the descriptor:</p>
   *
   * <pre>
   * (Ljava/lang/ModuleLayer;Ljava/lang/Class;)
   *     Ljava/util/ServiceLoader;
   * </pre>
   *
   * <p>It is rejected because the replacement loader does not support this
   * overload.</p>
   */
  @Test
  public void rejectsUnsupportedLoadModuleLayerOverload()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      method.visitInsn(Opcodes.ACONST_NULL);
                      method.visitLdcInsn(Type.getType(Runnable.class));

                      method.visitMethodInsn(Opcodes.INVOKESTATIC,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "load",
                                             "(Ljava/lang/ModuleLayer;Ljava/lang/Class;)" +
                                                 ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR,
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());
  }

  /**
   * Verifies that weaving is transactional at class level.
   *
   * <p>The generated method first contains a supported load(Class) invocation,
   * followed by an unsupported stream() invocation.</p>
   *
   * <p>The weaver may have already forwarded the supported instruction to its
   * internal ClassWriter when the unsupported instruction is encountered.
   * Nevertheless, the partially generated class must be discarded. The result
   * must contain the original bytes, including the original
   * java/util/ServiceLoader owner of the first invocation.</p>
   */
  @Test
  public void rejectsWholeClassWhenUnsupportedInvocationFollowsSupportedOne()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      emitLoad(method);
                      method.visitInsn(Opcodes.POP);

                      emitLoad(method);

                      method.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                             ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                                             "stream",
                                             "()Ljava/util/stream/Stream;",
                                             false);

                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());

    assertInvocationExists(result.getBytes(),
                           Opcodes.INVOKESTATIC,
                           ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                           "load",
                           "(Ljava/lang/Class;)Ljava/util/ServiceLoader;");

    assertNoInvocationExists(result.getBytes(),
                             Opcodes.INVOKESTATIC,
                             ServiceLoaderWeaver.OSGI_SERVICE_LOADER,
                             "load",
                             "(Ljava/lang/Class;)"+ ServiceLoaderWeaver.OSGI_SERVICE_LOADER_DESCRIPTOR);
  }

  /**
   * Verifies that a class with no ServiceLoader invocation is not woven.
   *
   * <p>The generated method performs only a String constant load and contains no
   * reference to java/util/ServiceLoader.</p>
   *
   * <p>The expected result reports failure/not-woven and returns the exact
   * original array. This also verifies that the weaver does not generate a new
   * class byte array unnecessarily.</p>
   */
  @Test
  public void doesNotWeaveClassWithoutServiceLoaderInvocation()
  {
    byte[] originalBytes =
      createClass(new MethodBody()
                  {
                    @Override
                    public void accept(MethodVisitor method)
                    {
                      method.visitLdcInsn("nothing to weave");
                      method.visitInsn(Opcodes.POP);
                    }
                  });

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());
  }

  /**
   * Verifies class-wide remapping of a ServiceLoader field when the class also
   * contains a supported ServiceLoader invocation.
   *
   * <p>The generated class is equivalent to:</p>
   *
   * <pre>{@code
   * class GeneratedFieldConsumer {
   *
   *   private java.util.ServiceLoader<Runnable> loader;
   *
   *   static void consume() {
   *     java.util.ServiceLoader.load(Runnable.class);
   *   }
   * }
   * }</pre>
   *
   * <p>After weaving, the field descriptor must change from:</p>
   *
   * <pre>
   * Ljava/util/ServiceLoader;
   * </pre>
   *
   * <p>to:</p>
   *
   * <pre>
   * Lcom/aicas/osgi/spi/proxy/ServiceLoader;
   * </pre>
   *
   * <p>The generic field signature must also be remapped by ClassRemapper.</p>
   */
  @Test
  public void remapsFieldDescriptorWhenSupportedInvocationExists()
  {
    byte[] originalBytes =
      createClassWithServiceLoaderField(true);

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertTrue(result.isSuccess());

    assertFieldDescriptorExists(result.getBytes(),
                                "loader",
                                ServiceLoaderWeaver.OSGI_SERVICE_LOADER_DESCRIPTOR);

    assertNoFieldDescriptorExists(result.getBytes(),
                                  "loader",
                                  ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR);
  }

  /**
   * Verifies that a ServiceLoader type reference alone does not activate
   * weaving.
   *
   * <p>The generated class contains a field of type
   * java.util.ServiceLoader<Runnable>, but no ServiceLoader method invocation.
   * Because the weaving policy requires at least one supported invocation, the
   * class must remain unchanged.</p>
   */
  @Test
  public void doesNotRemapFieldWithoutInvocation()
  {
    byte[] originalBytes =
      createClassWithServiceLoaderField(false);

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(originalBytes);

    assertFalse(result.isSuccess());
    assertSame(originalBytes, result.getBytes());

    assertFieldDescriptorExists(result.getBytes(),
                                "loader",
                                ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR);
  }

  /**
   * Verifies failure handling for malformed class-file bytes.
   *
   * <p>The input is not a valid JVM class file and causes ClassReader
   * construction or parsing to fail. The weaver must catch the transformation
   * exception, report an unsuccessful result, and return the exact original
   * byte array.</p>
   */
  @Test
  public void invalidClassBytesAreReturnedUnchanged()
  {
    byte[] invalidBytes = { (byte) 0xCA, (byte) 0xFE,
            (byte) 0xBA, (byte) 0xBE };

    ServiceLoaderWeaver.WeavingResult result =
      ServiceLoaderWeaver.weave(invalidBytes);

    assertFalse(result.isSuccess());
    assertSame(invalidBytes, result.getBytes());
  }

  /**
   * Emits bytecode equivalent to:
   *
   * <pre>{@code
   * java.util.ServiceLoader.load(Runnable.class)
   * }</pre>
   *
   * <p>The generated invocation leaves the resulting ServiceLoader instance on
   * the operand stack. The caller must either consume it with another method
   * invocation or remove it using {@link Opcodes#POP}.</p>
   *
   * @param method target method visitor
   */
  private static void emitLoad(MethodVisitor method)
  {
    method.visitLdcInsn(Type.getType(Runnable.class));

    method.visitMethodInsn(Opcodes.INVOKESTATIC,
                           ServiceLoaderWeaver.JAVA_SERVICE_LOADER,
                           "load",
                           "(Ljava/lang/Class;)Ljava/util/ServiceLoader;",
                           false);
  }

  /**
   * Generates a synthetic class named {@code test.GeneratedConsumer}.
   *
   * <p>The generated class contains:</p>
   *
   * <ul>
   *   <li>a public default constructor;</li>
   *   <li>a public static {@code consume()} method;</li>
   *   <li>the bytecode supplied by {@code body} inside {@code consume()}.</li>
   * </ul>
   *
   * <p>The class is generated entirely in memory and is never written to a
   * {@code .class} file.</p>
   *
   * @param body callback that emits the body of the generated consume method
   *
   * @return generated JVM class-file bytes
   */
  private static byte[] createClass(MethodBody body)
  {
    ClassWriter writer =
      new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);

    writer.visit(Opcodes.V17,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "test/GeneratedConsumer",
                 null,
                 "java/lang/Object",
                 null);

    addDefaultConstructor(writer);

    MethodVisitor method =
      writer.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                         "consume",
                         "()V",
                         null,
                         null);

    method.visitCode();
    body.accept(method);
    method.visitInsn(Opcodes.RETURN);
    method.visitMaxs(0, 0);
    method.visitEnd();

    writer.visitEnd();
    return writer.toByteArray();
  }

  private static byte[] createClassWithServiceLoaderField(boolean includeSupportedInvocation)
  {
    ClassWriter writer =
      new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);

    writer.visit(Opcodes.V17,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "test/GeneratedFieldConsumer",
                 null,
                 "java/lang/Object",
                 null);

    FieldVisitor field =
      writer.visitField(Opcodes.ACC_PRIVATE,
                        "loader",
                        ServiceLoaderWeaver.JAVA_SERVICE_LOADER_DESCRIPTOR,
                        "Ljava/util/ServiceLoader<Ljava/lang/Runnable;>;",
                        null);

    field.visitEnd();

    addDefaultConstructor(writer);

    if (includeSupportedInvocation)
      {
        MethodVisitor method =
          writer.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                             "consume",
                             "()V",
                             null,
                             null);

        method.visitCode();
        emitLoad(method);
        method.visitInsn(Opcodes.POP);
        method.visitInsn(Opcodes.RETURN);
        method.visitMaxs(0, 0);
        method.visitEnd();
      }

    writer.visitEnd();
    return writer.toByteArray();
  }

  private static void addDefaultConstructor(ClassWriter writer)
  {
    MethodVisitor constructor =
      writer.visitMethod(Opcodes.ACC_PUBLIC,
                         "<init>",
                         "()V",
                         null,
                         null);

    constructor.visitCode();
    constructor.visitVarInsn(Opcodes.ALOAD, 0);

    constructor.visitMethodInsn(Opcodes.INVOKESPECIAL,
                                "java/lang/Object",
                                "<init>",
                                "()V",
                                false);

    constructor.visitInsn(Opcodes.RETURN);
    constructor.visitMaxs(0, 0);
    constructor.visitEnd();
  }

  private static void assertInvocationExists(byte[] bytes,
                                             int expectedOpcode,
                                             String expectedOwner,
                                             String expectedName,
                                             String expectedDescriptor)
  {
    List<Invocation> invocations = readInvocations(bytes);

    Invocation expected = new Invocation(expectedOpcode, expectedOwner,
                                         expectedName,
                                         expectedDescriptor);

    assertTrue("Expected invocation was not found. Existing invocations: " +
               invocations,
               invocations.contains(expected));
  }

  private static void assertNoInvocationExists(byte[] bytes,
                                               int opcode,
                                               String owner,
                                               String name,
                                               String descriptor)
  {
    List<Invocation> invocations = readInvocations(bytes);

    Invocation unexpected =
      new Invocation(opcode,
                     owner,
                     name,
                     descriptor);

    assertFalse(
                "Unexpected invocation was found: " + unexpected,
                invocations.contains(unexpected));
  }

  /**
   * Reads all ordinary method invocation instructions from a generated class.
   *
   * <p>This helper is used to inspect the output of the weaver. It does not load
   * or execute the generated class.</p>
   *
   * @param bytes class-file bytes to inspect
   *
   * @return invocation instructions in visitation order
   */
  private static List<Invocation> readInvocations(byte[] bytes)
  {
    final List<Invocation> invocations =
      new ArrayList<Invocation>();

    new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9)
                                  {
                                    @Override
                                    public MethodVisitor visitMethod(int access,
                                                                     String name,
                                                                     String descriptor,
                                                                     String signature,
                                                                     String[] exceptions)
                                    {
                                      return new MethodVisitor(Opcodes.ASM9)
                                      {
                                        @Override
                                        public void visitMethodInsn(int opcode,
                                                                    String owner,
                                                                    String methodName,
                                                                    String methodDescriptor,
                                                                    boolean isInterface)
                                        {
                                          invocations.add(new Invocation(
                                                                         opcode,
                                                                         owner,
                                                                         methodName,
                                                                         methodDescriptor));
                                        }
                                      };
                                    }
                                  },
                                  ClassReader.SKIP_DEBUG |
                                     ClassReader.SKIP_FRAMES);

    return invocations;
  }

  /**
   * Verifies that selected bytecode locations no longer reference
   * java/util/ServiceLoader.
   *
   * <p>The inspection currently covers:</p>
   *
   * <ul>
   *   <li>field descriptors;</li>
   *   <li>field generic signatures;</li>
   *   <li>method descriptors;</li>
   *   <li>method generic signatures;</li>
   *   <li>method invocation owners;</li>
   *   <li>method invocation descriptors;</li>
   *   <li>type instructions;</li>
   *   <li>class literals loaded using LDC.</li>
   * </ul>
   *
   * @param bytes woven class-file bytes
   */
  private static void assertNoReferenceToJavaServiceLoader(byte[] bytes)
  {
    final List<String> references =
      new ArrayList<String>();

    new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9)
                                  {
                                    @Override
                                    public FieldVisitor visitField(int access,
                                                                   String name,
                                                                   String descriptor,
                                                                   String signature,
                                                                   Object value)
                                    {
                                      collectReference(references,
                                                       "field " + name,
                                                       descriptor);

                                      collectReference(references,
                                                       "field signature " + name,
                                                       signature);

                                      return null;
                                    }

                                    @Override
                                    public MethodVisitor visitMethod(int access,
                                                                     String name,
                                                                     String descriptor,
                                                                     String signature,
                                                                     String[] exceptions)
                                    {
                                      collectReference(references,
                                                       "method " + name,
                                                       descriptor);

                                      collectReference(references,
                                                       "method signature " +  name,
                                                       signature);

                                      return new MethodVisitor(Opcodes.ASM9)
                                      {
                                        @Override
                                        public void visitMethodInsn(int opcode,
                                                                    String owner,
                                                                    String methodName,
                                                                    String methodDescriptor,
                                                                    boolean isInterface)
                                        {
                                          if (ServiceLoaderWeaver.JAVA_SERVICE_LOADER.equals(owner))
                                            {
                                              references.add("invocation owner " +
                                                             owner + "." +
                                                             methodName +
                                                             methodDescriptor);
                                            }

                                          collectReference(references,
                                                           "invocation descriptor " + methodName,
                                                           methodDescriptor);
                                        }

                                        @Override
                                        public void visitTypeInsn(int opcode,
                                                                  String type)
                                        {
                                          if (ServiceLoaderWeaver.JAVA_SERVICE_LOADER.equals(type))
                                            {
                                              references.add("type instruction " +
                                                             type);
                                            }
                                        }

                                        @Override
                                        public void visitLdcInsn(Object value)
                                        {
                                          if (value instanceof Type)
                                            {
                                              Type type = (Type) value;

                                              if (type.getSort() == Type.OBJECT &&
                                                  ServiceLoaderWeaver.JAVA_SERVICE_LOADER.equals(type.getInternalName()))
                                                {
                                                  references.add("class literal " +  value);
                                                }
                                            }
                                        }
                                      };
                                    }
                                  },
                                  0);

    assertTrue("Remaining java.util.ServiceLoader references: " + references,
               references.isEmpty());
  }

  private static void collectReference(List<String> references,
                                       String location,
                                       String value)
  {
    if (value != null &&
        value.contains(ServiceLoaderWeaver.JAVA_SERVICE_LOADER))
      {
        references.add(location + ": " + value);
      }
  }

  private static void assertFieldDescriptorExists(
                                                  byte[] bytes,
                                                  String expectedName,
                                                  String expectedDescriptor)
  {
    List<FieldDescription> fields = readFields(bytes);

    FieldDescription expected =
      new FieldDescription(
                           expectedName,
                           expectedDescriptor);

    assertTrue("Expected field was not found. Existing fields: " + fields,
               fields.contains(expected));
  }

  private static void assertNoFieldDescriptorExists(
                                                    byte[] bytes,
                                                    String fieldName,
                                                    String descriptor)
  {
    List<FieldDescription> fields = readFields(bytes);

    FieldDescription unexpected =
      new FieldDescription(
                           fieldName,
                           descriptor);

    assertFalse("Unexpected field was found: " + unexpected,
                fields.contains(unexpected));
  }

  private static List<FieldDescription> readFields(byte[] bytes)
  {
    final List<FieldDescription> fields =
      new ArrayList<FieldDescription>();

    new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9)
                                  {
                                    @Override
                                    public FieldVisitor visitField(int access,
                                                                   String name,
                                                                   String descriptor,
                                                                   String signature,
                                                                   Object value)
                                    {
                                      fields.add(
                                                 new FieldDescription(
                                                                      name,
                                                                      descriptor));

                                      return null;
                                    }
                                  },
                                  ClassReader.SKIP_CODE |
                                     ClassReader.SKIP_DEBUG |
                                     ClassReader.SKIP_FRAMES);

    return fields;
  }

  private interface MethodBody
  {
    void accept(MethodVisitor methodVisitor);
  }

  private static final class Invocation
  {
    private final int opcode;
    private final String owner;
    private final String name;
    private final String descriptor;

    private Invocation(int opcode,
                       String owner,
                       String name,
                       String descriptor)
    {
      this.opcode = opcode;
      this.owner = owner;
      this.name = name;
      this.descriptor = descriptor;
    }

    @Override
    public boolean equals(Object object)
    {
      if (this == object)
        {
          return true;
        }

      if (!(object instanceof Invocation))
        {
          return false;
        }

      Invocation other = (Invocation) object;

      return opcode == other.opcode && owner.equals(other.owner) &&
             name.equals(other.name) && descriptor.equals(other.descriptor);
    }

    @Override
    public int hashCode()
    {
      int result = Integer.valueOf(opcode).hashCode();
      result = 31 * result + owner.hashCode();
      result = 31 * result + name.hashCode();
      result = 31 * result + descriptor.hashCode();
      return result;
    }

    @Override
    public String toString()
    {
      return opcode + " " + owner + "." + name + descriptor;
    }
  }

  private static final class FieldDescription
  {
    private final String name;
    private final String descriptor;

    private FieldDescription(String name,
                             String descriptor)
    {
      this.name = name;
      this.descriptor = descriptor;
    }

    @Override
    public boolean equals(Object object)
    {
      if (this == object)
        {
          return true;
        }

      if (!(object instanceof FieldDescription))
        {
          return false;
        }

      FieldDescription other =
        (FieldDescription) object;

      return name.equals(other.name) && descriptor.equals(other.descriptor);
    }

    @Override
    public int hashCode()
    {
      return 31 * name.hashCode() + descriptor.hashCode();
    }

    @Override
    public String toString()
    {
      return name + ":" + descriptor;
    }
  }
}
